title: "Bruno Dalmônico Schossland"
description: "Desarrollador Web | UX/UI | Innovación Digital"
url: "https://bdalmonico.github.io"
baseurl: ""
theme: minima


show_excerpts: false
markdown: kramdown

header_pages:
  - README.md

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/bdalmonico" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/schossland" }
    - { platform: email, user_url: "mailto:b.dalmonico@gmail.com" }

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-avatar

seo:
  type: "profile"
  name: "Bruno Dalmônico Schossland"
  links:
    - "https://www.linkedin.com/in/schossland"
    - "https://github.com/bdalmonico"
