title: "Bruno Dalmônico Schossland"
description: "Desarrollador Web | UX/UI | Innovación Digital"
url: "https://brunodalmonico.github.io"
baseurl: ""
theme: minima

author:
  name: "Bruno Dalmônico Schossland"
  email: "b.dalmonico@gmail.com"
  location: "Monforte de Lemos, España"
  linkedin: "https://www.linkedin.com/in/brunodalmonico"
  github: "https://github.com/brunodalmonico"

show_excerpts: false
markdown: kramdown

header_pages:
  - README.md

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/brunodalmonico" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/brunodalmonico" }
    - { platform: email, user_url: "mailto:b.dalmonico@gmail.com" }

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-avatar

seo:
  type: "profile"
  name: "Bruno Dalmônico Schossland"
  links:
    - "https://www.linkedin.com/in/brunodalmonico"
    - "https://github.com/brunodalmonico"
